docs_dir: doc/book/ru
pages:
    - index.md
    - 'Передача аргументов при создание службы': 'creation-options.md'
    - 'Получение службы в зависимости от контекста': 'service-context.md'
site_name: container
site_description: 'Контейнер - расширение ServiceLocator'
repo_url: 'https://github.com/nnx-framework/container'
copyright: 'Copyright (c) 2016 <a href="https://github.com/nnx-framework">NNX</a>'
